apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  misas.toml: |
    # misas.toml
    # Binding for incoming connections
    [server]
    # If not set, will default to 0.0.0.0
    host = "0.0.0.0"
    # Default is 8084
    port = {{ .Values.service.internalPort | quote }} 
    # Default is 8085
    subscription_port = {{ .Values.service.internalPortSubscriptions | quote }} 
    [database]
    # Primary database
    [database.mongo]
    # Defaults to 0.0.0.0
    host = {{ template "mongodb.fullname" . }} 
    # Defaults to 27017
    user = {{ default "" .Values.mongodb.mongodbUsername | quote }} 
    password = {{ default "" .Values.mongodb.mongodbPassword | quote }}
    port = {{ default "" .Values.mongodb.mariadbDatabase | quote }}
    # Defaults to misas
    name = {{ default "misas" .Values.mongodb.mongodbDatabase | quote }} 
    [logs]
    # By default, logs are printed to stdout
    stdout = {{ default true .Values.log.stdout }} 
    # By default, logs are also exported to a local file misas.log
    file = {{ default true .Values.log.file }}
    filepath = "misas.log" 
    logLevel = {{ default "INFO" .Values.log.level | quote }}
